-- Base schema (direct apply): creates core tables used by the app

-- Matches
create table if not exists public.matches (
  id bigint generated by default as identity primary key,
  title text not null default 'eguchiman',
  start_points integer not null default 25000,
  oka_points integer not null,
  uma_low integer not null,
  uma_high integer not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Participants
create table if not exists public.participants (
  id bigint generated by default as identity primary key,
  match_id bigint not null references public.matches(id) on delete cascade,
  name text not null,
  seat_priority smallint not null check (seat_priority between 0 and 3),
  unique (match_id, name),
  unique (match_id, seat_priority)
);

-- Games
create table if not exists public.games (
  match_id bigint not null references public.matches(id) on delete cascade,
  number integer not null,
  created_at timestamptz not null default now(),
  primary key (match_id, number)
);

-- Game Scores (raw per-seat score per game)
create table if not exists public.game_scores (
  match_id bigint not null references public.matches(id) on delete cascade,
  game_number integer not null,
  seat_index smallint not null check (seat_index between 0 and 3),
  raw_score integer not null check (raw_score % 100 = 0),
  primary key (match_id, game_number, seat_index)
);

-- Game Seats: per-game seat -> participant mapping (for rotating seats)
create table if not exists public.game_seats (
  match_id bigint not null references public.matches(id) on delete cascade,
  game_number integer not null,
  seat_index smallint not null check (seat_index between 0 and 3),
  participant_id bigint not null references public.participants(id) on delete restrict,
  display_name text,
  primary key (match_id, game_number, seat_index)
);

create unique index if not exists game_seats_unique_participant_per_game
  on public.game_seats (match_id, game_number, participant_id);
