import { readFileSync, writeFileSync } from "node:fs";
import { stripTypeScriptTypes } from "node:module";
import path from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(scriptDir, "..");

const entries = [
  "frontend/historyUtils.ts",
  "frontend/routerUtils.ts",
  "frontend/app.ts",
];

for (const entry of entries) {
  const tsPath = path.join(rootDir, entry);
  const jsPath = tsPath.replace(/\.ts$/, ".js");
  const source = readFileSync(tsPath, "utf8");
  const output = stripTypeScriptTypes(source, {
    mode: "transform",
  });
  const banner = `// Auto-generated from ${entry}. Do not edit this file directly.\n`;
  writeFileSync(jsPath, `${banner}${output}`, "utf8");
  console.log(`${entry} -> ${path.relative(rootDir, jsPath)}`);
}
